name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  melodic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build for ROS Melodic
        env:
          NATIVE_DOCKER: ros:melodic-ros-base
        run: |
          docker run --rm -v $(pwd):/root/catkin_ws/src/vl53l1x_ros ${NATIVE_DOCKER} /bin/bash -c \
          "cd /root/catkin_ws && \
          rosdep install --from-paths src --ignore-src -y && \
          catkin_make && \
          catkin_make run_tests && catkin_test_results && \
          catkin_make install"
  noetic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build for ROS Noetic
        env:
          NATIVE_DOCKER: ros:noetic-ros-base
        run: |
          docker run --rm -v $(pwd):/root/catkin_ws/src/vl53l1x_ros ${NATIVE_DOCKER} /bin/bash -c \
          "cd /root/catkin_ws && \
          rosdep install --from-paths src --ignore-src -y && \
          catkin_make && \
          catkin_make run_tests && catkin_test_results && \
          catkin_make install"
